In [24]:
#Python store 1 dim data
#Numpy store 2D nad 3D
import numpy as np

In [2]:
list1=[1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [83]:
print("1 d Aarray")
a=np.array([1,2,3,4,5])
print(a)

1 d Aarray
[1 2 3 4 5]


In [88]:
np.sort(a)
np.concatenate((a, b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [87]:
print("2D array")
b=np.array([[2,3,4,5,6],
            [1,2,3,4,5]])
print(b)

2D array
[[2 3 4 5 6]
 [1 2 3 4 5]]


In [6]:
type(a)

numpy.ndarray

In [8]:
#Numper of element in array
print(a.size)

print(b.size)

5
10


In [9]:
#no of rows and col
print(a.shape)

(5,)


In [10]:
print(b.shape)

(2, 5)


In [11]:
print(a.dtype)

int32


In [12]:
print(b.dtype)

int32


In [13]:
b.transpose()

array([[2, 1],
       [3, 2],
       [4, 3],
       [5, 4],
       [6, 5]])

#Part2


In [17]:
np.empty((4,4),dtype=int)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 4259932, 5570643],
       [6029395, 7340097, 4456560, 7602273],
       [6029409, 7274572, 6357091,     108]])

In [18]:
#np.ones((rows,col),dtype=int)
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
c=np.zeros((4,8),dtype=str)
c=np.zeros((4,8),dtype=bool)
print(c)



[[False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]]
[[False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]]


#part3


In [ ]:
#np.arange(start,end,step)


In [35]:
a=np.arange(1,19)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [30]:
b=np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [39]:
#arr.reshape((r,c))
a.reshape((3,6))
b.reshape((10,5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [43]:
#rev of rehsape and revel not create any memory
a.flatten()
b.ravel()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Part 4

In [47]:
b=b.reshape((10,5))

In [48]:
b[0]

array([1, 3, 5, 7, 9])

In [50]:
b[0,4]

9

In [51]:
b[0:8]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79]])

In [53]:
#b=[r,c]
b[:,2]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [56]:
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [55]:
b[2:5,4]

array([29, 39, 49])

In [58]:
a=np.arange(0,18).reshape(6,3)
b=np.arange(20,38).reshape(6,3)
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [59]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [60]:
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [61]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [62]:
np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [63]:
b.max()

37

In [64]:
np.sum(b)

513

In [65]:
b.min()

20

In [66]:
b.argmax()#index

17

In [67]:
np.sum(b,axis=1)

array([ 63,  72,  81,  90,  99, 108])

In [ ]:
np.mean(b)

In [68]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576],
       [4.79583152, 4.89897949, 5.        ],
       [5.09901951, 5.19615242, 5.29150262],
       [5.38516481, 5.47722558, 5.56776436],
       [5.65685425, 5.74456265, 5.83095189],
       [5.91607978, 6.        , 6.08276253]])

In [70]:
np.random.random(2)
#exercise


array([0.43195928, 0.50928485])

In [71]:
np.random.random((2,2))

array([[0.00405333, 0.82671009],
       [0.5993883 , 0.76408059]])

In [72]:
np.random.random((2,10))

array([[0.1784439 , 0.54270793, 0.26769956, 0.75949996, 0.39231165,
        0.59081914, 0.29138815, 0.17811731, 0.08009699, 0.98441286],
       [0.18455503, 0.65026541, 0.5149278 , 0.95941064, 0.60549813,
        0.41953807, 0.94357608, 0.97623918, 0.16997673, 0.6581155 ]])

Part 7

In [75]:
s1="Anjali is going great sogtware engineer"
s2="Anjali faces 10 rejection"

In [76]:
np.char.add(s1,s2)

array('Anjali is going great sogtware engineerAnjali faces 10 rejection',
      dtype='<U64')

In [77]:
np.char.upper(s1)

array('ANJALI IS GOING GREAT SOGTWARE ENGINEER', dtype='<U39')

In [79]:
np.char.lower(s1)

array('anjali is going great sogtware engineer', dtype='<U39')

In [80]:
np.char.split(s1)

array(list(['Anjali', 'is', 'going', 'great', 'sogtware', 'engineer']),
      dtype=object)

In [81]:
np.char.replace(s1,'Anjali','Mitali')

array('Mitali is going great sogtware engineer', dtype='<U39')